# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Rene Rivera 2019.

version: "{build}"

environment:
  matrix:
  # - TOOLSET: msvc
  #   COMPILER_VERSION: 9.0
  #   platform: 32
  #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  # - TOOLSET: msvc
  #   COMPILER_VERSION: 10.0
  #   platform: 32
  #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  # - TOOLSET: msvc
  #   COMPILER_VERSION: 11.0
  #   platform: 32
  #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  # - TOOLSET: msvc
  #   COMPILER_VERSION: 12.0
  #   platform: 32
  #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  # - TOOLSET: msvc
  #   COMPILER_VERSION: 12.0
  #   platform: 64
  #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - TOOLSET: msvc
    COMPILER_VERSION: 14.0
    platform: 32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - TOOLSET: msvc
    COMPILER_VERSION: 14.0
    platform: 64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - TOOLSET: msvc
    COMPILER_VERSION: 14.1
    platform: 32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - TOOLSET: msvc
    COMPILER_VERSION: 14.1
    platform: 64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - TOOLSET: gcc
    CXXSTD: 11,14,17
    COMPILER: C:/MinGW/bin/g++.exe
    platform: 32
    COMPILER_PATH: C:/MinGW/bin
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - TOOLSET: gcc
    CXXSTD: 11,14,17
    COMPILER: C:/mingw-w64/x86_64-6.3.0-posix-seh-rt_v5-rev1/mingw64/bin/g++.exe
    platform: 64
    COMPILER_PATH: C:/mingw-w64/x86_64-6.3.0-posix-seh-rt_v5-rev1/mingw64/bin
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - TOOLSET: gcc
    CXXSTD: 11,14,17
    COMPILER: C:/mingw-w64/x86_64-7.3.0-posix-seh-rt_v5-rev0/mingw64/bin/g++.exe
    platform: 64
    COMPILER_PATH: C:/mingw-w64/x86_64-7.3.0-posix-seh-rt_v5-rev0/mingw64/bin
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - TOOLSET: gcc
    CXXSTD: 11,14,17
    COMPILER: C:/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/g++.exe
    platform: 64
    COMPILER_PATH: C:/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

install:
  - cd %APPVEYOR_BUILD_FOLDER%/..
  - curl "https://github.com/boostorg/build/archive/develop.zip" -L -o b2.zip
  - 7z x b2.zip
  - cd build-develop
  - ./bootstrap.bat

build: off

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - "echo using %TOOLSET% ^: %COMPILER_VERSION% ^: %COMPILER% ^; > project-config.jam"
  - type project-config.jam
  - set BOOST_BUILD_PATH=%APPVEYOR_BUILD_FOLDER%/../build-develop
  - cd tests
  - set Path=%Path%;%COMPILER_PATH%
  - "%APPVEYOR_BUILD_FOLDER%/../build-develop/b2 toolset=%TOOLSET% address-model=%PLATFORM% cxxstd=%CXXSTD% -j2"
